var rule = {
	title: '风车动漫',
	host: 'https://www.fcdmp.xyz',
	homeUrl: '/',
	url: '/index.php/vod/type/id/fyclass/',
	searchUrl: '/index.php/vod/search.html?wd=**',
	searchable: 2,
	quickSearch: 0,
	filterable: 0,
	headers: {
		'User-Agent': 'MOBILE_UA',
	},
	timeout: 5000,
	class_name: '日漫&剧场版&国创&欧美',
	class_url: '1&2&3&4',
	play_parse: true,
	lazy: '',
	limit: 6,
	推荐: '.module-poster-item;a&&title;.module-item-pic img&&data-original;.module-item-note&&Text;a&&href',
	一级: '.module-poster-item;a&&title;.module-item-pic img&&data-original;.module-item-note&&Text;a&&href',
	二级: {
		title: 'h1&&Text',
		img: '.module-item-pic img&&data-original',
		desc: '.video-info-items:eq(3)&&Text;.video-info-items:eq(2)&&Text;.video-info-items:eq(1)&&Text',
		content: '.vod_content&&Text',
		tabs: '.module-tab-item',
		lists: '.module-play-list:eq(#id) a'
	},
	搜索: '.module-poster-item;a&&title;.module-item-pic img&&data-original;.module-item-note&&Text;a&&href',
}
